<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-3APH7UC" failures="1" tests="5" name="Personal Loan" time="0.212" errors="0" timestamp="2023-11-08T13:10:57 IST">
  <testcase classname="Test.day2" name="ploan" time="0.015"/>
  <testcase classname="Test.day4" name="APILoginHomeloan" time="0.003"/>
  <testcase classname="Test.day4" name="MobileLoginHomeloan" time="0.003"/>
  <testcase classname="Test.day4" name="WebLoginHomeloan" time="0.006"/>
  <testcase classname="Test.day1" name="Demo" time="0.073">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.day1.Demo(day1.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
